name: test-in-toto

on: [pull_request]

jobs:
  test_in_toto_action:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    name: Install in-toto and test presence in path
    steps:
    - uses: actions/checkout@v2
    - name: Install in-toto
      uses: ./
    - name: Check install
      run: in-toto version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi